### ISSUE TITLE
Web framework benchmark

### ISSUE THREAD

**Issue by waghanza** [Ethosa/akane#1]
Hi @Ethosa  ,

Do you want to add `akane` in https://github.com/the-benchmarker/web-frameworks ?

The purpose of this benchmark is to compare frameworks on a simple (an homogeneous) way.

We have already :

+ `jester`
+ `httpbeast`

Wdyt ?

Regards,

**Comment by Ethosa** [comment]
Yes, it would be nice. Sorry to notice this issue just now.

**Comment by waghanza** [comment]
I've tried to do it myself, but I have compilation errors. Do you have time to give a try ?

The features are very few, 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

**Comment by Ethosa** [comment]
hmm ... it should be something like that? https://github.com/Ethosa/akane/blob/master/tests/test8/main.nim
![image](https://user-images.githubusercontent.com/49402667/83750777-fdfd6e00-a68f-11ea-9130-f0df7982421d.png)
![image](https://user-images.githubusercontent.com/49402667/83750801-0a81c680-a690-11ea-8ccb-e2880d0d1c8b.png)
